#!/bin/sh
#  _    _          ___           __ _     (R)
# | |  (_)_ _____ / __|___ _ _  / _(_)__ _
# | |__| \ V / -_) (__/ _ \ ' \|  _| / _` |
# |____|_|\_/\___|\___\___/_||_|_| |_\__, |
#                                    |___/
# Copyright (c) 2009-2015 Keppler IT GmbH.
# ----------------------------------------------------------------------------
# liveconfig-meta/postinst
# Debian package "post-installation" script
# https://github.com/liveconfig/meta/
# ----------------------------------------------------------------------------

set -e

case "$1" in
	configure)
		# continue
	;;
	abort-upgrade|abort-remove|abort-deconfigure)
		exit 0;
	;;
	*)
		echo "LiveConfig postinst called with unknown argument '$1'" >&2
		exit 0
	;;
esac

if [ "$1" = "configure" -a -z "$2" ]; then
	# first install (not an upgrade)

	# enable some apache modules after installation:
	if [ -x /usr/sbin/a2enmod ]; then
		/usr/sbin/a2enmod actions include rewrite ssl suexec
		/usr/sbin/a2dismod status
	fi

	# set "ServerTokens" and "TraceEnable" to safer values
	if [ -f /etc/apache2/conf.d/security ]; then
		sed -i -e "s/^ServerTokens .*/ServerTokens Prod/" \
		       -e "s/^TraceEnable On/TraceEnable Off/i" \
		       /etc/apache2/conf.d/security
	fi

	# adjust suPHP settings:
	if [ -f /etc/suphp/suphp.conf ]; then
		sed -i -e 's/^check_vhost_docroot=true/check_vhost_docroot=false/' \
		       -e 's/^umask=0077/umask=0022/i' \
		       /etc/suphp/suphp.conf
		if ! grep -q '^application/x-httpd-php=' /etc/suphp/suphp.conf; then
			sed -i -e 's/^\(;Handler for php-scripts\)/\1\napplication\/x-httpd-php="php:\/usr\/bin\/php-cgi"/i' \
			       /etc/suphp/suphp.conf
		fi
	fi

	# reload Apache configuration
	if [ -x /etc/init.d/apache2 ]; then
		/etc/init.d/apache2 reload
	fi
fi

exit 0

# <EOF>-----------------------------------------------------------------------
